---
abstract: 'Distributed Make: A perl module for running pipelines'
author:
  - 'Kiran V Garimella <kiran@well.ox.ac.uk> and Warren W. Kretzschmar <warren.kretzschmar@well.ox.ac.uk>'
build_requires:
  File::Path: '0'
  FindBin: '0'
  Test::Files: '0'
  Test::More: '0'
  strictures: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DM
requires:
  Carp: '0'
  File::Basename: '0'
  File::NFSLock: '0'
  File::Temp: '0'
  File::Tempdir: '0'
  Getopt::Std: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util::TypeConstraints: '0'
  MooseX::StrictConstructor: '0'
  Net::OpenSSH: '0'
  Sys::Hostname: '0'
  YAML::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.013'
